### ISSUE TITLE
HIGH: Eliminate Massive CSS Bloat and Duplication

### ISSUE THREAD

**Issue by HexMakina** [ounss/Copro-Academy#1]
# CSS Architecture Refactor: Eliminate Bloat & Improve Maintainability

## Problem Statement

The current CSS architecture has significant bloat, repetition, and maintainability issues across `style.css` (1,087 lines) and `admin.css` (1,089 lines). 

### 1. **Dual CSS Architecture Inefficiency**
- `style.css`: Front-end styles with inconsistent patterns
- `admin.css`: Well-structured intrinsic design system
- **~40% overlap** in functionality (buttons, forms, typography, layout)

### 2. **Variable Usage Inconsistencies**
```css
/* Good: Using variables */
color: var(--primary-blue);

/* Bad: Hard-coded values scattered throughout */
color: #3a5db0;
background: #f8f9fa;
padding: 1rem 2rem;
```

### 3. **Repetitive Patterns**
```css
/* Repeated 15+ times with minor variations */
.card, .formation-card, .related-card, .benefit-card {
  background: var(--white);
  border-radius: var(--border-radius);
  box-shadow: var(--shadow);
  transition: var(--transition);
}
```

### 4. **Overly Specific Selectors**
```css
/* 🚫 Unmaintainable */
.grid-container.list-view .card-content h2

/* ✅ Composable */
.card-title
```

### 5. **Inline Styles Present**
Found in templates:
```html
<div style="background: #e74c3c; color: white; padding: 1rem;">
```

### 6. **Non-Composable Architecture**
- Missing utility classes for common patterns
- Monolithic component definitions
- No systematic spacing/sizing scale

### Phase 1: CSS Variable System
```css
:root {
  /* Unified spacing scale */
  --space-xs: 0.25rem;
  --space-sm: 0.5rem;
  --space-md: 1rem;
  --space-lg: 1.5rem;
  --space-xl: 2rem;
  
  /* Typography scale */
  --text-xs: clamp(0.75rem, 0.7rem + 0.2vw, 0.8rem);
  --text-sm: clamp(0.85rem, 0.8rem + 0.25vw, 0.9rem);
  --text-base: clamp(0.9rem, 0.85rem + 0.25vw, 1rem);
  
  /* Component tokens */
  --button-height: 2.5rem;
  --input-height: 2.75rem;
  --card-padding: var(--space-lg);
}
```

### Phase 2: Composable Components
```css
/* Base button */
.btn {
  padding: var(--space-sm) var(--space-lg);
  border-radius: var(--radius-base);
  border: 1px solid var(--color-border);
  min-height: var(--button-height);
}

/* Variants */
.btn--primary { background: var(--color-primary); }
.btn--sm { min-height: var(--button-height-sm); }
```

### Phase 3: Utility Classes
```css
/* Spacing utilities */
.p-md { padding: var(--space-md); }
.mt-lg { margin-top: var(--space-lg); }

/* Layout utilities */
.flex { display: flex; }
.items-center { align-items: center; }
.gap-md { gap: var(--space-md); }
```

## Implementation Strategy

1. **Audit**: Remove unused selectors (~200 lines estimated savings)
2. **Consolidate**: Merge CSS files into single system
3. **Systematize**: Replace hard-coded values with variables
4. **Componentize**: Convert monolithic styles to composable classes
5. **Eliminate Inline**: Move all inline styles to classes
6. **Optimize**: Remove repetitive patterns

## Expected Outcomes

- **~60% size reduction** (from 2,176 lines to ~870 lines)
- **Consistent design system** across admin/front-end
- **Improved maintainability** with composable components
- **Better performance** with reduced CSS payload
- **Developer experience** improvement with predictable classes

## Success Metrics

- [ ] Single CSS file under 1,000 lines
- [ ] Zero inline styles in templates
- [ ] 100% CSS variable usage for design tokens
- [ ] Composable utility classes for common patterns
- [ ] No duplicate functionality between admin/front-end

---

**Priority: High** | **Effort: Medium** | **Impact: High**

*This refactor aligns with the project's "every bit counts" philosophy and will significantly improve maintainability while reducing bundle size.*
